### PR TITLE
Fix: use cache for screenshots

### LINKED ISSUE #10: bug: screenshots get recreated every time
no matter if they exist already or not, the plugin will recreate the screenshots.

with many videos this adds a lot of unnecessary time to the build process

### PR DESCRIPTION
**Pull request by axe312ger**
closes #10

### CODE REVIEW

**Comment by Coderwelsch** [comment]
Dear @axe312ger … do you know why the build has failed? Your fix would be awesome, because the screenshot rendering takes sooooo long while developing bigger sites … That would help me soooo much 😍

**Comment by axe312ger** [comment]
@Coderwelsch yes, its so annoying. It just takes screenshots, always :D

Definitely want to fix it, lets see if I manage it today (famous last words ™️)

**Comment by axe312ger** [comment]
It builds on another PR <3 

Needed to actually build the plugin before running the example :)

**Comment by axe312ger** [comment]
This seems to help now. For cold builds it will still create the screenshots.

I'll release soon and then we can give it a try

**Comment by axe312ger** [comment]
@Coderwelsch so the 0.3.5 should have this PR, but I am pretty sure it won't fix it properly.

I am about to release 0.4.0 as I finished rewriting the whole thing to TypeScript plus fixes plenty of small bugs, improved logging and introduced a new caching principle which should drastically reduce duplicate transforms & screenshots.

**Comment by Coderwelsch** [comment]
Dear @axe312ger , I am really sorry that I am missed your updates (4d ago). Somehow I didn’t turn on notifications 🙈. Thank you so much for your effort! I am currently trying your updates. As long as the screenshots won’t be generated every time in dev / watch mode, I would be pretty happy! I will you reach you out after trying some things … 

❤️

**Comment by Coderwelsch** [comment]
Do you already started with the typescript rewrite? I don’t know typescript that much so that I could help you … 🙈

**Comment by Coderwelsch** [comment]
I tried the version 0.4.5 and it worked like a charme ☺️. It now uses the cached screenshots after the initial generation. Thank you 🙏

**Comment by axe312ger** [comment]
@Coderwelsch THANKS! Great to hear. Yes I rewrote it with the help of @zcei (🙏 ) last weekend :)

For me it unfortunately does not work yet. I get a bunch of `RequestError:getaddrinfo ENOTFOUND videos.ctfassets.net` when I try it on my customer project.

How many videos do you have? How big are the biggest ones? How many of the big ones you got? Do you source from Contentful or from your disk?

I have about 33 videos, 2 of them are kinda big (100+mb). It works fine for 31, but it has issues downloading the big ones from Contentful. I think this PR should fix the issue: https://github.com/gatsbyjs/gatsby/pull/33461

**Comment by Coderwelsch** [comment]
I had some problemes caused by my locally installed ffmpeg and fprobe versions after I upgraded to 0.4.5. After I switched to the binaries downloaded by gatbsy-transform-video I solved that issue. I don’t know if my problem corresponds to yours … But you can give it a try :-)

**Comment by axe312ger** [comment]
I tackled the issue with the Gatsby team and the next Gatsby v4 release will fix the downloading of the videos.

No updates need to be done to this plugin, except I might enforce the upcoming Gatsby version.

**Pull request merged**
